address_descriptors = false
author = "Themefisher"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "This is meta description"
email = "contact@citysbestsounds.com"
favicon = "images/favicon.png"
google_tag_manager = "<!-- Google Tag Manager --> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-M7HZMW8');</script> <!-- End Google Tag Manager -->"
image = "images/CBS_logo.png"
location = "3432 Tanterra Cir, Brookeville, MD  20833"
logo = "images/logo.png"
logo_text = "City's Best Sounds"
logo_width = "150px"
navbar_fixed = false
phone = "601-880-3914"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = true
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "schedule a session"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/citysbestsounds/"
title = "instagram"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
